<!DOCTYPE html>
<html lang="en"><head>
<script src="blackbox_presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="blackbox_presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="blackbox_presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="blackbox_presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="blackbox_presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="blackbox_presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="blackbox_presentation_files/libs/quarto-html/quarto-syntax-highlighting-4279360f14831a022364d2ef6b4efa56.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Todd R. Johnson">
  <meta name="dcterms.date" content="2026-03-25">
  <title>Black Box as a Diagnostic Reasoning Benchmark</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="blackbox_presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="blackbox_presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="blackbox_presentation_files/libs/revealjs/dist/theme/quarto-0fde88a82f0356838740f155f1088782.css">
  <link href="blackbox_presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="blackbox_presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="blackbox_presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="blackbox_presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Black Box as a Diagnostic Reasoning Benchmark</h1>
  <p class="subtitle">Assessing LLM Capabilities in Hidden State Identification<br><span style="font-size: 0.6em; color: #888;">Slides last updated March 19, 2026</span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Todd R. Johnson 
</div>
        <p class="quarto-title-affiliation">
            University of Texas Health Science Center at Houston
          </p>
    </div>
</div>

  <p class="date">2026-03-25</p>
</section>
<section id="clinical-reasoning-at-scale" class="slide level2">
<h2>Clinical Reasoning at Scale</h2>
<p>LLMs are being deployed across clinical reasoning tasks at unprecedented speed.</p>
<ul>
<li><p><strong>In 2024, 31.5% of 2,174 US hospitals</strong> deployed generative AI in clinical workflows;</p>
<ul>
<li>another <strong>24.7% planned near-term adoption</strong> <span class="citation" data-cites="everson2025genai">(<a href="#/references" role="doc-biblioref" onclick="">Everson, Nong, and Richwine 2025</a>)</span></li>
</ul></li>
<li><p><strong>2024 survey with responses from 43 of 67 Scottsdale Institute health systems</strong> all reported active AI adoption in clinical documentation (ambient listening) <span class="citation" data-cites="poon2025">(<a href="#/references" role="doc-biblioref" onclick="">Poon et al. 2025</a>)</span></p></li>
<li><p>Publications evaluating LLMs in clinical medicine: <strong>1 (2019) → 557 (2024)</strong> <span class="citation" data-cites="shool2025systematic">(<a href="#/references" role="doc-biblioref" onclick="">Shool et al. 2025</a>)</span></p></li>
</ul>
<p><strong>Scope of deployment:</strong> Triage · Differential diagnosis · Clinical documentation · Test ordering · Referral decisions · Prior authorization · Coding · Treatment planning</p>
<aside class="notes">
<p>I want to start with the scope of what’s happening. A third of US hospitals are already running generative AI in clinical workflows. A national survey of leading health systems found universal adoption activity. The research literature has more than tripled in a single year. And the applications span the full range of clinical cognitive work — not just documentation, which is relatively low-risk, but diagnosis, triage, test ordering, treatment planning. Tasks that require clinical reasoning. The question is: what’s the evidentiary basis for this deployment?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-case-for-deployment" class="slide level2">
<h2>The Case for Deployment</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="benchmark-milestones">Benchmark Milestones</h3>
<ul>
<li><p><strong>Med-PaLM 2</strong>: Expert-level medical question answering <span class="citation" data-cites="singhal2023medpalm2">(<a href="#/references" role="doc-biblioref" onclick="">Singhal et al. 2023</a>)</span></p></li>
<li><p><strong>GPT-4</strong>: ~86% on USMLE-style questions, exceeding passing threshold by 20+ points</p></li>
<li><p><strong>AMIE</strong>: Outperformed primary care physicians in structured diagnostic conversations (Tu et al.&nbsp;2024)</p></li>
</ul>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<h3 id="clinical-evidence">Clinical Evidence</h3>
<ul>
<li><p><strong>LLM alone: 92%</strong> diagnostic accuracy vs.&nbsp;74% for physicians (Goh et al.&nbsp;2024, JAMA Network Open)</p></li>
<li><p><strong>MASAI trial</strong>: AI-assisted mammography detected 20% more cancers, halved radiologist workload (Lång et al.&nbsp;2023)</p></li>
<li><p><strong>Danish screening</strong>: AI reliably filtered ~50% of normal chest X-rays (Plesner et al.&nbsp;2024)</p></li>
</ul>
</div></div>
<p><br></p>
<p>If you’re a health system CEO looking at these numbers, deployment seems like an obvious decision.</p>
<aside class="notes">
<p>And the evidence looks compelling. On the benchmark side, Med-PaLM 2 reached expert-level performance on medical question answering. GPT-4 crushed the USMLE by twenty points. Google’s AMIE outperformed primary care physicians in structured diagnostic conversations. On the clinical side, Goh et al.&nbsp;ran a randomized trial where the LLM alone scored 92% on diagnostic reasoning — physicians scored 74%. The MASAI trial found AI-assisted mammography caught 20% more cancers while halving radiologist workload. If you’re a health system CEO looking at these numbers, deployment seems like an obvious decision. But there’s a problem.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pattern-recognition-clinical-reasoning" class="slide level2" data-background-color="#1a1a2e">
<h2>Pattern Recognition ≠ Clinical Reasoning</h2>
<div class="conflict-thesis">
<p>Healthcare is adopting LLMs for tasks that require clinical reasoning, based on benchmark evidence that measures something other than clinical reasoning.</p>
</div>
<p>Three independent lines of evidence:</p>
<div class="evidence-block">
<p><span class="evidence-num"><strong>1.</strong></span> <strong>Context matching, not reasoning</strong> (Wen et al.&nbsp;2025, <em>npj Digital Medicine</em>)</p>
<p>Rephrase a clinical question with synonymous terms → different (wrong) answer. Present a scenario where no answer is correct → models confidently pick one. Tested across 8 models: assumptions underlying MCQA validity <strong>globally invalidated</strong>.</p>
</div>
<div class="evidence-block">
<p><span class="evidence-num"><strong>2.</strong></span> <strong>Base rate neglect is systematic</strong> (Omar et al.&nbsp;2025)</p>
<p>Add “recently returned from Southeast Asia” to a fever-and-cough vignette → LLMs shift to malaria/dengue even when pneumonia remains far more likely. <strong>300 vignettes, 20 models</strong> — salient cue overrides base rate every time.</p>
</div>
<div class="evidence-block">
<p><span class="evidence-num"><strong>3.</strong></span> <strong>Reasoning traces don’t reflect actual computation</strong></p>
<p>Models given incorrect hints construct elaborate justifications without acknowledging the hint (Anthropic faithfulness study; Matton et al.&nbsp;2025). Models trained on <em>wrong</em> intermediate steps paired with correct answers still improve (Kambhampati et al.&nbsp;2025). Reasoning models show sharp performance collapse at complexity thresholds (Shojaee et al.&nbsp;2025).</p>
</div>
<aside class="notes">
<p>Here’s the core problem. Three independent research programs converge on the same conclusion.</p>
<p>First, Wen and colleagues at Mayo tested whether LLM performance on medical board-style questions reflects applied knowledge or pattern matching. They rephrased clinical questions using synonymous terms — same clinical scenario, different surface features — and got different, wrong answers. When they presented scenarios with no correct answer choice, models confidently selected one anyway. They tested eight models and globally invalidated the assumptions underlying these benchmarks.</p>
<p>Second, Omar and colleagues found what they call “chasing zebras.” Add a single salient cue — recent travel to Southeast Asia — to a routine fever-and-cough vignette, and LLMs shift to rare tropical diagnoses even when community-acquired pneumonia remains far more probable. Three hundred vignettes, twenty models, completely systematic.</p>
<p>Third — and this is the deepest problem — even the reasoning traces that models produce may not reflect their actual computation. Anthropic’s own research found that models given incorrect hints will use the hint to get the right answer but then write an explanation that pretends they solved it independently. Kambhampati’s group showed that models trained on deliberately wrong reasoning steps still improve, as long as the final answer is correct. The trace isn’t reasoning — it’s a learned navigation pattern through latent space. And Shojaee and colleagues showed that reasoning models experience sharp performance collapse once problems exceed certain complexity thresholds.</p>
<p>Now — some of Shojaee’s specific findings have been contested on methodological grounds, and the debate is ongoing. But that’s actually the point. If the field can’t agree on whether these models are truly reasoning even on puzzle tasks, we certainly shouldn’t assume they’re reasoning on clinical problems.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="whats-needed" class="slide level2">
<h2>What’s Needed</h2>
<p>If clinical reasoning deployment is outrunning our ability to evaluate clinical reasoning, we need benchmarks that:</p>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="out-of-distribution">Out-of-Distribution</h3>
<p>Problems not solvable by pattern matching to training data. No memorization shortcuts.</p>
<h3 id="computable-optimality-ceiling">Computable Optimality Ceiling</h3>
<p>Know how far from perfect a model is — not just pass/fail.</p>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<h3 id="decomposable">Decomposable</h3>
<p>Isolate which component processes fail. Pinpoint the source of reasoning breakdown.</p>
<h3 id="process-oriented">Process-Oriented</h3>
<p>Evaluate <em>how</em> the model reasons, not just whether it gets the right answer.</p>
</div></div>
<p><br></p>
<p><strong>Diagnostic reasoning</strong> is the best-characterized component of clinical reasoning — multicausal abductive inference with identifiable component processes (Johnson &amp; Krems 2001). I have a task that tests all of them.</p>
<aside class="notes">
<p>So what do we do? We need evaluation that actually tests reasoning. Four properties. Out-of-distribution, so we’re not measuring memorization. An optimality ceiling, so we know how far from perfect a model is, not just whether it passes some threshold. Decomposable, so we can identify which component process is failing. And process-oriented, so we’re evaluating how the model reasons, not just whether it gets the right answer.</p>
<p>Now, the problem I’ve described is broad — it applies to clinical reasoning generally. But I’m going to study it through diagnostic reasoning specifically, for two reasons. First, diagnostic reasoning is the most cognitively well-characterized form of clinical reasoning. My work with Josef Krems established that it’s multicausal abductive inference — reasoning from observed effects to hidden causes under uncertainty — with identifiable component processes: hypothesis generation, test selection, constraint tracking, belief updating. Second, I have a task environment that lets me test all of these components, with ground truth and a computable optimality ceiling. Let me show you.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<p>OLDER</p>
</section>
<section id="ai-in-clinical-diagnosis-today" class="slide level2 smaller">
<h2>AI in Clinical Diagnosis Today</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>LLMs are now embedded across clinical workflows:</p>
<ul>
<li><strong>31.5%</strong> of US hospitals deployed generative AI in clinical workflows by 2024, with another 24.7% planning near-term implementation <span class="citation" data-cites="everson2025genai">(<a href="#/references" role="doc-biblioref" onclick="">Everson, Nong, and Richwine 2025</a>)</span></li>
<li>Publications on LLMs in medical diagnostics surged from 160 (2023) to <strong>557</strong> (2024) <span class="citation" data-cites="shool2025systematic">(<a href="#/references" role="doc-biblioref" onclick="">Shool et al. 2025</a>)</span></li>
<li>Primary applications: triage, differential diagnosis, clinical note drafting, referral recommendations</li>
<li>Emergency medicine and radiology lead direct diagnostic use</li>
</ul>
<p><span class="citation" data-cites="thirunavukarasu2023llmmed">Thirunavukarasu et al. (<a href="#/references" role="doc-biblioref" onclick="">2023</a>)</span> reviewed the initial wave in 2023; the field has since accelerated dramatically.</p>
</div><div class="column" style="width:45%;">
<h3 id="milestone-results">Milestone Results</h3>
<ul>
<li><strong>Med-PaLM 2</strong>: Expert-level medical question answering <span class="citation" data-cites="singhal2023medpalm2">(<a href="#/references" role="doc-biblioref" onclick="">Singhal et al. 2023</a>)</span></li>
<li><strong>AMIE</strong>: Outperformed primary care physicians in structured diagnostic conversations <span class="citation" data-cites="tu2024amie">(<a href="#/references" role="doc-biblioref" onclick="">Tu et al. 2024</a>)</span></li>
<li><strong>Swedish MASAI trial</strong>: AI-assisted mammography detected <strong>20% more cancers</strong> while cutting radiologist workload in half (80,000+ women) <span class="citation" data-cites="lang2023masai">(<a href="#/references" role="doc-biblioref" onclick="">Lång et al. 2023</a>)</span></li>
</ul>
</div></div>
<aside class="notes">
<p>Set the stage with concrete adoption numbers. A third of US hospitals are already using generative AI clinically. The research literature has exploded — over 500 papers in 2024 alone. Thirunavukarasu’s 2023 Nature Medicine review captured the first wave, but the pace has intensified since then. Med-PaLM 2 matched experts on medical QA. Google’s AMIE beat primary care physicians in structured diagnostic conversations. The Swedish MASAI trial — over 80,000 women — found AI-assisted mammography identified 20% more cancers while halving radiologist workload. These results are driving clinical adoption.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-case-for-adoption-ai-outperforming-clinicians" class="slide level2 smaller">
<h2>The Case for Adoption: AI Outperforming Clinicians</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>A growing body of evidence shows LLMs exceeding physician performance on diagnostic tasks <span class="citation" data-cites="goh2024llmdiagnosis">(<a href="#/references" role="doc-biblioref" onclick="">Goh et al. 2024</a>)</span>:</p>
<table class="caption-top">
<caption>Diagnostic reasoning scores across six clinical cases (50 physicians, JAMA Network Open)</caption>
<thead>
<tr class="header">
<th></th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LLM alone</strong></td>
<td><strong>92%</strong></td>
</tr>
<tr class="even">
<td>Physicians + LLM</td>
<td>76%</td>
</tr>
<tr class="odd">
<td>Physicians alone</td>
<td>74%</td>
</tr>
</tbody>
</table>
<ul>
<li>Danish chest X-ray screening: AI reliably filtered <strong>~50%</strong> of normal scans, freeing radiologists for complex cases <span class="citation" data-cites="plesner2024chestxray">(<a href="#/references" role="doc-biblioref" onclick="">Plesner et al. 2024</a>)</span></li>
<li>MIT–Harvard study: Radiologists shown AI predictions systematically <strong>undervalued</strong> the AI input relative to their own judgment <span class="citation" data-cites="yu2024radiologist">(<a href="#/references" role="doc-biblioref" onclick="">Yu et al. 2024</a>)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Paradox</strong></p>
</div>
<div class="callout-content">
<p>Physicians with AI barely outperform physicians without AI — but <strong>AI alone</strong> dramatically outperforms both.</p>
<p>This “automation neglect” pattern appears consistently across imaging, clinical reasoning, and diagnostic accuracy studies.</p>
</div>
</div>
</div>
<div class="fragment">
<p>If AI is this capable on benchmarks and structured evaluations, shouldn’t we deploy it widely?</p>
</div>
</div></div>
<aside class="notes">
<p>Now why is adoption accelerating so fast? Because the results are remarkable. Goh et al.&nbsp;in JAMA Network Open ran a randomized clinical trial with 50 physicians: the LLM alone scored 92% on diagnostic reasoning, physicians with LLM access scored 76%, and physicians without AI scored 74%. The combined human-AI approach barely beat unaided physicians. A Danish study found AI could reliably filter about half of all normal chest X-rays, freeing radiologists for the hard cases. The MIT-Harvard study showed that even when the AI was right, radiologists systematically underweighted its input. Topol and Rajpurkar reviewed this pattern across multiple studies — it’s consistent. So the enthusiasm is understandable. But should we trust these results?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-evaluation-crisis" class="slide level2 smaller">
<h2>The Evaluation Crisis</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="the-deployment-gap">The Deployment Gap</h3>
<p>LLMs tested in isolation vs.&nbsp;deployed with real users <span class="citation" data-cites="bean2026reliability">(<a href="#/references" role="doc-biblioref" onclick="">Bean et al. 2026</a>)</span>:</p>
<table class="caption-top">
<caption>Randomized trial, 1,298 participants, 10 medical scenarios (Nature Medicine)</caption>
<thead>
<tr class="header">
<th></th>
<th>Condition identified</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LLM alone</strong></td>
<td><strong>94.9%</strong></td>
</tr>
<tr class="even">
<td>Real users + LLM</td>
<td>34.5%</td>
</tr>
<tr class="odd">
<td>Control (Google)</td>
<td>~34%</td>
</tr>
</tbody>
</table>
<p>Real users with the <em>same</em> LLMs performed <strong>no better than Googling it</strong>.</p>
<p>In one case, two users describing identical subarachnoid hemorrhage symptoms received opposite advice — one told to “lie down in a dark room,” the other correctly referred to emergency care.</p>
</div><div class="column" style="width:50%;">
<h3 id="why-benchmarks-fail">Why Benchmarks Fail</h3>
<p><strong>“Context matching,” not reasoning</strong> <span class="citation" data-cites="wen2025context">(<a href="#/references" role="doc-biblioref" onclick="">Wen et al. 2025</a>)</span>: Models match keywords in the question to answer choices. Rephrase the same clinical question with synonymous terms → different (wrong) answer. When <em>no</em> answer choice is correct, models confidently pick one anyway.</p>
<p><strong>“Chasing zebras”</strong> <span class="citation" data-cites="omar2025zebras">(<a href="#/references" role="doc-biblioref" onclick="">Omar et al. 2025</a>)</span>: Add “recently returned from Southeast Asia” to a fever-and-cough vignette → LLMs shift to malaria or dengue, even when community-acquired pneumonia remains far more likely. Tested across 300 vignettes and 20 models — base rate neglect is systematic.</p>
<p><strong>“Illusion of thinking”</strong> <span class="citation" data-cites="shojaee2025illusion">(<a href="#/references" role="doc-biblioref" onclick="">Shojaee et al. 2025</a>)</span>: Reasoning models appear to deliberate but performance <strong>collapses</strong> at problem complexity thresholds.</p>
</div></div>
<div class="fragment">
<blockquote>
<p><strong>Core question</strong>: Does high benchmark performance reflect diagnostic reasoning — or sophisticated pattern matching?</p>
</blockquote>
</div>
<aside class="notes">
<p>But here’s the problem. Bean et al.&nbsp;in Nature Medicine ran a randomized trial with 1,298 participants: LLMs scored 94.9% on medical scenarios when tested alone, but when real people used the same LLMs, accuracy dropped to 34.5% — no better than just Googling it. In one case, two users described the same subarachnoid hemorrhage symptoms and got opposite advice. One was told to lie down in a dark room, the other to go to the ER. That’s a catastrophic failure mode.</p>
<p>Then the deeper benchmarking problems. Wen et al.&nbsp;showed that high MCQA scores reflect context matching, not reasoning. What does that mean concretely? If you rephrase a clinical question using synonymous terms — same clinical scenario, different wording — models give different, wrong answers. And when you present a scenario where none of the answer choices are correct, models confidently pick one anyway. They’re matching surface patterns, not reasoning about the clinical situation.</p>
<p>Omar et al.&nbsp;found what they call “chasing zebras.” Add an incidental mention of travel to a clinical vignette — say, a patient with fever and cough who recently returned from Southeast Asia — and LLMs shift to rare tropical diagnoses like malaria or dengue even when community-acquired pneumonia is far more probable. This was tested across 300 vignettes and 20 different models. Base rate neglect is systematic. And Shojaee et al.&nbsp;showed that even reasoning models that appear to think through problems experience sharp performance collapses at complexity thresholds. All of this means: we may be measuring the wrong things.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-is-diagnostic-reasoning" class="slide level2 smaller">
<h2>What IS Diagnostic Reasoning?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Component</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Hypothesis generation</strong></td>
<td>Propose candidate explanations</td>
</tr>
<tr class="even">
<td><strong>Test selection</strong></td>
<td>Choose informative observations</td>
</tr>
<tr class="odd">
<td><strong>Constraint tracking</strong></td>
<td>Maintain consistent evidence</td>
</tr>
<tr class="even">
<td><strong>Belief updating</strong></td>
<td>Revise hypotheses with new data</td>
</tr>
<tr class="odd">
<td><strong>Spatial reasoning</strong></td>
<td>Navigate physical/conceptual spaces</td>
</tr>
<tr class="even">
<td><strong>Integration</strong></td>
<td>Combine all components iteratively</td>
</tr>
</tbody>
</table>
<p>Diagnostic reasoning is <strong>multicausal abductive inference</strong> — reasoning from observed effects to hidden causes under uncertainty <span class="citation" data-cites="johnson2001abductive">(<a href="#/references" role="doc-biblioref" onclick="">Johnson and Krems 2001</a>)</span>.</p>
</div><div class="column" style="width:50%;">
<div class="fragment">
<h3 id="what-we-know-from-cognitive-science">What We Know from Cognitive Science</h3>
<ul>
<li>People use <strong>current explanations</strong> to guide hypothesis selection, but apply them inconsistently across contexts <span class="citation" data-cites="johnson2001abductive">(<a href="#/references" role="doc-biblioref" onclick="">Johnson and Krems 2001</a>)</span></li>
<li>Memory demands alter reasoning <strong>strategy</strong> but not necessarily <strong>accuracy</strong> — people compensate by selectively prioritizing prior explanations <span class="citation" data-cites="klichowicz2021memory">(<a href="#/references" role="doc-biblioref" onclick="">Klichowicz et al. 2021</a>)</span></li>
<li>Abductive reasoning is fundamentally harder than deductive prediction <span class="citation" data-cites="liu2024incomplete">(<a href="#/references" role="doc-biblioref" onclick="">Liu, Neubig, and Andreas 2024</a>)</span></li>
</ul>
</div>
</div></div>
<aside class="notes">
<p>Before we can test diagnostic reasoning, we need to define what it is. My prior work with Josef Krems established that diagnostic reasoning is multicausal abductive inference — reasoners must integrate multiple candidate explanations while accumulating evidence. The key finding: people use their current explanation to guide hypothesis selection, but inconsistently — sometimes anchoring when they shouldn’t. Klichowicz and Krems later showed that memory demands change reasoning strategies without necessarily hurting accuracy — people compensate by prioritizing existing explanations. Both findings are directly relevant: LLMs face analogous challenges in maintaining working hypotheses across multi-turn diagnostic interactions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="we-need-a-controlled-lab" class="slide level2">
<h2>We Need a Controlled Lab</h2>
<p>Four requirements for a diagnostic reasoning benchmark:</p>
<div class="columns">
<div class="column" style="width:25%;">
<div class="fragment">
<h3 id="out-of-distribution-1">Out-of-Distribution</h3>
<p>Problems not in training data. No memorization shortcuts.</p>
</div>
</div><div class="column" style="width:25%;">
<div class="fragment">
<h3 id="ground-truth">Ground Truth</h3>
<p>Verifiable correct answers. No ambiguity.</p>
</div>
</div><div class="column" style="width:25%;">
<div class="fragment">
<h3 id="decomposable-1">Decomposable</h3>
<p>Can isolate component processes. Pinpoint failures.</p>
</div>
</div><div class="column" style="width:25%;">
<div class="fragment">
<h3 id="integrated">Integrated</h3>
<p>Tests the full diagnostic loop, not just individual skills.</p>
</div>
</div></div>
<aside class="notes">
<p>Here are the four properties we need. Out-of-distribution so we’re not just testing memorization. Verifiable ground truth so we know when the model is right or wrong. Decomposable so we can identify which component is failing. And integrated so we test the full diagnostic loop, not just isolated skills.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="enter-black-box" class="slide level2">
<h2>Enter Black Box</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Black Box</strong> (Eric Solomon, 1978)</p>
<ul>
<li>8×8 grid with 4 hidden atoms</li>
<li>Fire rays from edges, observe outcomes</li>
<li>Deduce atom positions from ray behavior</li>
<li>Three ray outcomes: <strong>Hit</strong>, <strong>Reflection</strong>, <strong>Detour</strong></li>
</ul>
<p>The game naturally requires:</p>
<ul>
<li>Generating hypotheses about hidden states</li>
<li>Selecting informative tests (rays)</li>
<li>Tracking constraints as evidence accumulates</li>
<li>Updating beliefs when contradicted</li>
</ul>
</div><div class="column" style="width:45%;">
<p><img data-src="ray_physics.png" style="width:100.0%" alt="Black Box game board showing ray physics: absorption, deflection, and reflection"></p>
<p><em>Screenshot placeholder — use React app Sandbox mode or hand-drawn diagram showing absorption, deflection, and reflection examples on an 8×8 grid.</em></p>
</div></div>
<aside class="notes">
<p>Black Box is a deduction game from 1978. You fire rays into an 8x8 grid and observe where they come out. From these observations, you deduce where 4 hidden atoms are located. The game is perfect for our purposes because it naturally requires all the component processes of diagnostic reasoning. It’s essentially a miniature diagnostic problem with verifiable ground truth.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="black-box-as-diagnostic-instrument" class="slide level2">
<h2>Black Box as Diagnostic Instrument</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="diagnostic-process">Diagnostic Process</h3>
<ol type="1">
<li>Generate differential diagnosis</li>
<li>Select next diagnostic test</li>
<li>Track ruled-out conditions</li>
<li>Revise hypothesis with new results</li>
<li>Interpret spatial relationships</li>
<li>Integrate evidence iteratively</li>
</ol>
</div><div class="column" style="width:50%;">
<h3 id="black-box-analog">Black Box Analog</h3>
<ol type="1">
<li>Hypothesize atom positions</li>
<li>Choose which ray to fire</li>
<li>Track eliminated positions</li>
<li>Update hypothesis after ray result</li>
<li>Trace ray paths through grid</li>
<li>Combine ray evidence to final guess</li>
</ol>
</div></div>
<div class="fragment">
<p><strong>Key advantage</strong>: Every game instance is a unique, out-of-distribution problem with known ground truth and quantifiable optimal solutions.</p>
</div>
<aside class="notes">
<p>This is the “aha” slide. Every step of diagnostic reasoning maps directly to a Black Box analog. The critical advantage is that unlike medical cases, every Black Box game has a mathematically optimal solution. We can compute exactly how well a perfect reasoner would do. And because there are 635,376 possible configurations, these problems are genuinely out-of-distribution — you can’t memorize them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="research-questions" class="slide level2">
<h2>Research Questions</h2>
<ol type="1">
<li class="fragment">Can LLMs perform <strong>forward reasoning</strong> — predicting ray behavior from known atom positions?</li>
<li class="fragment">Can LLMs perform <strong>inverse reasoning</strong> — deducing hidden atoms from ray observations?</li>
<li class="fragment">How do <strong>model scale</strong>, <strong>prompt engineering</strong>, and <strong>extended thinking</strong> affect performance?</li>
<li class="fragment">Where in the performance corridor do LLMs fall — between <strong>chance</strong> and <strong>optimal</strong>?</li>
<li class="fragment">Which <strong>component processes</strong> of diagnostic reasoning fail?</li>
<li class="fragment">What does this imply for <strong>diagnostic AI deployment</strong>?</li>
</ol>
<aside class="notes">
<p>Six questions that structure the entire talk. We’ll go through each of these systematically. The first two establish baseline capabilities. Question 3 tests our interventions. Question 4 puts results in context. Question 5 is the diagnostic contribution. And question 6 connects back to the clinical stakes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ray-physics" class="slide level2" data-background-color="#f0f0f0">
<h2>Ray Physics</h2>
<div class="columns">
<div class="column" style="width:33%;">
<h3 id="absorption-hit">Absorption (Hit)</h3>
<p>Ray strikes an atom <strong>directly</strong> and is absorbed.</p>
<p>No exit position recorded.</p>
</div><div class="column" style="width:33%;">
<h3 id="reflection">Reflection</h3>
<p>Atom diagonally adjacent to <strong>entry point</strong> causes ray to reverse.</p>
<p>Ray exits where it entered.</p>
</div><div class="column" style="width:34%;">
<h3 id="deflection-detour">Deflection (Detour)</h3>
<p>Single adjacent atom <strong>deflects</strong> ray 90° away from the atom.</p>
<p>Multiple deflections possible.</p>
</div></div>
<div class="fragment">
<p><strong>Complexity</strong>: Rays can interact with 0–4 atoms. Deflection chains create paths traversing many cells, making spatial tracking increasingly difficult.</p>
</div>
<aside class="notes">
<p>Three types of ray interactions. Absorption is straightforward — the ray hits an atom head-on. Reflection is trickier — it happens when an atom is diagonally adjacent to where the ray enters the grid. Deflection is the most complex — atoms adjacent to the ray’s path bend it 90 degrees, and multiple deflections create complex zigzag paths. This is where spatial reasoning really gets tested.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-modes-partial-decomposition" class="slide level2">
<h2>Two Modes: Partial Decomposition</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="predict-mode-forward">Predict Mode (Forward)</h3>
<ul>
<li>Atoms are <strong>visible</strong></li>
<li>Model predicts ray exit position</li>
<li>Tests <strong>spatial reasoning</strong> in isolation</li>
<li>“Given these atoms, what happens to this ray?”</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="play-mode-inverse">Play Mode (Inverse)</h3>
<ul>
<li>Atoms are <strong>hidden</strong></li>
<li>Model fires rays, deduces positions</li>
<li>Tests <strong>full diagnostic loop</strong></li>
<li>Hypothesis generation → test selection → constraint tracking → belief updating</li>
</ul>
</div></div>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Cross-Mode Pattern</th>
<th>Implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Good Predict + Poor Play</td>
<td>Non-spatial limitations (abduction, constraints, test selection)</td>
</tr>
<tr class="even">
<td>Poor Predict + Poor Play</td>
<td>Spatial/world model partly responsible</td>
</tr>
<tr class="odd">
<td>Performance delta</td>
<td>Isolates inferential machinery contribution</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>We use two modes to partially decompose capabilities. Predict mode isolates spatial reasoning — the atoms are visible, just predict what happens to a ray. Play mode tests the full diagnostic loop — atoms are hidden, the model must fire rays and figure out where the atoms are. Comparing across modes lets us isolate which component processes are failing.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<h3 data-background-color="#2C3E50" style="text-align: center; color: white;" id="live-demo">Live Demo</h3>
<div style="font-size: 1.5em; margin-top: 2em;">
<p><strong>Switch to React app in browser</strong></p>
</div>
<div style="font-size: 1.2em; margin-top: 1em; color: #ecf0f1;">
<ol type="1">
<li><strong>Sandbox Mode</strong> — Learn the ray physics</li>
<li><strong>Play Mode</strong> — Try the reasoning yourself</li>
<li><strong>LLM Mode</strong> — Watch Claude play (optional)</li>
</ol>
</div>
<aside class="notes">
<p>DEMO TIME. ~4-5 minutes. Start in Sandbox mode where atoms are visible — fire a few rays to show absorption, reflection, and deflection. Then switch to Play mode — ask the audience to suggest rays and watch them try to reason about atom positions. This builds empathy for how hard the task actually is. Optionally show LLM mode briefly if time permits.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="experimental-design" class="slide level2">
<h2>Experimental Design</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Factorial Design</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Factor</th>
<th>Levels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model</strong></td>
<td>Haiku 4.5, Sonnet 4.5, Sonnet 4.6, Opus 4.5, Opus 4.6</td>
</tr>
<tr class="even">
<td><strong>Prompt</strong></td>
<td>Baseline, Augmented</td>
</tr>
<tr class="odd">
<td><strong>Thinking</strong></td>
<td>Standard, Extended</td>
</tr>
<tr class="even">
<td><strong>VoT</strong></td>
<td>None + 3 visualization prompts</td>
</tr>
<tr class="odd">
<td><strong>Config</strong></td>
<td>10 fixed atom configurations</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<p><strong>Scale</strong></p>
<ul>
<li>Predict: 40 conditions × ~24 rays × 10 configs</li>
<li>Play: 80 conditions × 10 configs = 800 games</li>
<li>~1,200 unique experimental conditions total</li>
</ul>
<div class="fragment">
<p><strong>VoT Conditions</strong> (Play only):</p>
<ul>
<li>A: Grid State visualization</li>
<li>B: Ray Trace visualization</li>
<li>C: Hypothesis visualization</li>
</ul>
</div>
</div></div>
<aside class="notes">
<p>The full experimental design. Five Claude models spanning the capability range. Two prompt styles — baseline gives human-equivalent instructions, augmented adds detailed strategy and worked examples. Extended thinking gives the model a scratchpad. VoT adds visualization-of-thought prompts. All tested across 10 fixed atom configurations for reproducibility. This gives us about 1,200 unique experimental conditions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-optimal-solver" class="slide level2">
<h2>The Optimal Solver</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Information-theoretic strategy</strong>:</p>
<ul>
<li>Enumerate all C(64,4) = <strong>635,376</strong> candidate configurations</li>
<li>Each ray partitions candidates by outcome</li>
<li>Select ray minimizing E[remaining candidates]</li>
<li>Greedy strategy: best ray at each step</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Optimal Solver Results</strong></p>
</div>
<div class="callout-content">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Mean rays to solve: 7.6
Range: 5–9
Mean score: 11.3
All 10 configs solved: TRUE</code></pre>
</div>
</div>
</div>
</div>
</div>
</div></div>
<div class="fragment">
<p>This establishes the <strong>ceiling</strong> of the performance corridor — the best any agent can achieve with perfect rationality and unlimited computation.</p>
</div>
<aside class="notes">
<p>The optimal solver gives us the upper bound on performance. It searches all 635,376 possible configurations, picks the ray that eliminates the most candidates on average, and repeats. It solves all 10 configurations in about 7 rays on average. This is the ceiling — no agent, human or AI, can do better. Note this is a greedy strategy, which is itself a lower bound on optimal — true optimal via full lookahead would be even better, but greedy is already very strong.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chance-baseline" class="slide level2">
<h2>Chance Baseline</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Random guessing</strong> (fire zero rays, guess 4 positions):</p>
<p><span class="math display">\[X \sim \text{Hypergeometric}(N=64,\; K=4,\; n=4)\]</span></p>
<ul>
<li>E[atoms correct] = <strong>0.25</strong> out of 4</li>
<li>E[score] = <strong>18.75</strong> (5 × 3.75 missed atoms)</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="blackbox_presentation_files/figure-revealjs/unnamed-chunk-2-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<h3 id="performance-corridor">Performance Corridor</h3>
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Agent</th>
<th>E[Atoms]</th>
<th>E[Score]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Chance</strong></td>
<td>0.25</td>
<td>18.75</td>
</tr>
<tr class="even">
<td><strong>LLMs</strong></td>
<td>?</td>
<td>?</td>
</tr>
<tr class="odd">
<td><strong>Optimal</strong></td>
<td>4.00</td>
<td>11.3</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Any agent that extracts meaningful signal from ray observations should <strong>substantially exceed</strong> the chance baseline.</p>
</div>
</div></div>
<aside class="notes">
<p>The floor of the performance corridor. If you just guess randomly without firing any rays, you get 0.25 atoms correct on average and a score of 18.75. The vast majority of the time — 77% — you get zero atoms right. We now have our corridor: chance at 0.25 atoms, optimal at 4.0 atoms. Where do LLMs fall?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="predict-leaderboard-forest-plot" class="slide level2 smaller">
<h2>Predict: Leaderboard &amp; Forest Plot</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/predict-forest-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Here’s the full predict mode leaderboard as a forest plot. Each row is a unique experimental condition, ranked by accuracy. Note the model clustering — Opus models tend to cluster at top, Haiku at bottom. The best conditions achieve around 80% accuracy. This is forward reasoning only — given atoms, predict ray behavior. Already we see substantial error rates.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="predict-factor-effects" class="slide level2">
<h2>Predict: Factor Effects</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/predict-factors-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Marginal effects for each factor. Model matters most — clear separation between Haiku and Opus. Extended thinking and augmented prompts both help, but the gains are modest. VoT has minimal effect in predict mode. Key takeaway: model scale is the dominant factor for forward spatial reasoning.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-complexity-cliff" class="slide level2">
<h2>The Complexity Cliff</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/complexity-plots-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Two views of the complexity cliff. Left: as path length increases (more cells traveled), accuracy drops sharply. All models show this drop, but weaker models collapse faster. Right: as more atoms interact with a ray (higher atom density), accuracy decreases. This is direct evidence that spatial reasoning degrades with complexity. The models can handle simple, short paths but struggle with the complex deflection chains that require tracking multiple interactions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="play-leaderboard-forest-plot" class="slide level2 smaller">
<h2>Play: Leaderboard &amp; Forest Plot</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/play-forest-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Play mode forest plot — the full diagnostic reasoning task. Much lower performance than predict mode, as expected. The best conditions find about 2-3 atoms out of 4. Note that the chance baseline is 0.25 — all conditions beat chance, confirming LLMs extract some signal. But no condition gets close to 4.0 (optimal). Also notice the wider confidence intervals — play mode has higher variance across games.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="play-factor-effects" class="slide level2">
<h2>Play: Factor Effects</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/play-factors-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Play mode factor effects. Model still matters most, but the pattern is interesting — extended thinking sometimes helps, sometimes doesn’t, depending on the model. Augmented prompts show a clearer benefit in play mode than predict mode, probably because the game is more complex and benefits from strategic guidance. VoT conditions show mixed results — some visualization prompts actually hurt performance.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-performance-corridor" class="slide level2" data-background-color="#f8f9fa">
<h2>The Performance Corridor</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/performance-corridor-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>KEY SLIDE. The performance corridor. Chance at 0.25, optimal at 4.0, and LLMs in between. The crucial observation: all models are significantly above chance — they DO extract signal from ray observations. But they’re also far below optimal — there’s a massive gap to perfect performance. Even the best model is closer to chance than to optimal on an absolute scale. This gap represents the diagnostic reasoning deficit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="llm-vs-optimal-rays-used" class="slide level2">
<h2>LLM vs Optimal: Rays Used</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/optimal-rays-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Configuration-by-configuration comparison of rays used. Blue is the optimal solver, green is the best LLM condition, orange is the overall LLM mean. LLMs consistently use 2-3× as many rays as optimal. This is the test selection problem — LLMs are not choosing informative rays. They fire redundant rays that don’t narrow the candidate space efficiently. Direct analog to ordering redundant lab tests.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="llm-vs-optimal-score" class="slide level2">
<h2>LLM vs Optimal: Score</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/optimal-score-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Same comparison but for total score — which combines ray costs AND missed atom penalties. The gap is even larger here because LLMs both use more rays AND miss more atoms. The chance baseline at 18.75 shows that LLMs are well above chance, but the gap to optimal is substantial. Some configurations are much harder than others — note how the lines diverge on harder configs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cross-mode-comparison" class="slide level2">
<h2>Cross-Mode Comparison</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/cross-mode-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Head-to-head comparison. Blue is predict mode — forward reasoning. Red is play mode — full diagnostic loop. The gap is consistent across all models: forward reasoning is easier than inverse reasoning. This makes theoretical sense — prediction is deductive, diagnosis is abductive. But the gap also reveals that the inferential machinery (hypothesis generation, test selection, constraint tracking) adds substantial difficulty beyond just spatial reasoning.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="error-analysis-predict-mode" class="slide level2">
<h2>Error Analysis: Predict Mode</h2>
<aside class="notes">
<p>What kinds of errors do models make in predict mode? Deterministic classification — we compare what the model predicted versus what actually happens. Missed reflections are the most common error across all models — the reflection rule is the hardest physics to apply correctly. Off-by-one path errors indicate cell-by-cell tracking failures. The error profiles are surprisingly similar across models, suggesting these are fundamental difficulties with the ray physics rather than model-specific weaknesses.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="error-analysis-play-mode" class="slide level2">
<h2>Error Analysis: Play Mode</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="blackbox_presentation_files/figure-revealjs/play-errors-spatial-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="blackbox_presentation_files/figure-revealjs/play-errors-det-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Two complementary views of play mode errors. Left: LLM-as-judge classification into spatial versus non-spatial failures. Non-spatial errors — experiment design, constraint tracking, belief updating — dominate across all models. Right: deterministic analysis. Models pick optimal rays only a fraction of the time, with typical ray ranks around 5-10 out of 32 possible rays. They also fire excess rays after the solution is already determinable — they don’t know when to stop.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="scaling-effects" class="slide level2">
<h2>Scaling Effects</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/scaling-1.png" width="1344" class="r-stretch"><aside class="notes">
<p>Scaling from Haiku to Opus. Both modes improve with model size, but the gap between predict and play performance persists. Larger models are better at spatial reasoning AND at the full diagnostic loop, but they don’t close the gap between the two. This suggests the diagnostic reasoning deficit isn’t just a matter of scale — it’s a qualitative limitation in how these models integrate component processes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="factor-summary" class="slide level2">
<h2>Factor Summary</h2>
<table class="caption-top">
<colgroup>
<col style="width: 32%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Factor</th>
<th style="text-align: center;">Predict</th>
<th style="text-align: center;">Play</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model scale</strong></td>
<td style="text-align: center;">↑↑</td>
<td style="text-align: center;">↑↑</td>
<td>Dominant factor in both modes</td>
</tr>
<tr class="even">
<td><strong>Augmented prompt</strong></td>
<td style="text-align: center;">↑</td>
<td style="text-align: center;">↑</td>
<td>Consistent but modest benefit</td>
</tr>
<tr class="odd">
<td><strong>Extended thinking</strong></td>
<td style="text-align: center;">↑</td>
<td style="text-align: center;">— / ↑</td>
<td>Helps predict; mixed in play</td>
</tr>
<tr class="even">
<td><strong>VoT: Grid State</strong></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td>Minimal effect</td>
</tr>
<tr class="odd">
<td><strong>VoT: Ray Trace</strong></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">— / ↓</td>
<td>No help; sometimes hurts</td>
</tr>
<tr class="even">
<td><strong>VoT: Hypothesis</strong></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td>No consistent effect</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Key finding</strong>: No prompt intervention closes the gap to optimal. The limitations are architectural, not instructional.</p>
</div>
<aside class="notes">
<p>Summary table. Model scale is the only factor with consistent, large effects. Everything else is marginal. The sobering conclusion: you can’t prompt your way to diagnostic reasoning. Extended thinking helps with forward spatial reasoning but has mixed effects on the full diagnostic loop. VoT prompts — which add explicit visualization instructions — don’t reliably help and sometimes hurt. The limitations appear to be in the model’s ability to maintain and manipulate internal state, not in the instructions it receives.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="benchmark-context" class="slide level2">
<h2>Benchmark Context</h2>
<p>How does Black Box compare to other reasoning benchmarks?</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Benchmark</th>
<th>Task Type</th>
<th style="text-align: center;">OOD?</th>
<th style="text-align: center;">Ceiling?</th>
<th style="text-align: center;">Decomposable?</th>
<th style="text-align: center;">Process?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ZebraLogic</td>
<td>Constraint satisfaction</td>
<td style="text-align: center;">Partial</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="even">
<td>ConstraintBench</td>
<td>Constraint satisfaction</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="odd">
<td>BALROG</td>
<td>Game playing</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Partial</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="even">
<td>PuzzlePlex</td>
<td>Puzzle solving</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="odd">
<td><strong>Black Box</strong></td>
<td><strong>Diagnostic reasoning</strong></td>
<td style="text-align: center;"><strong>Yes</strong></td>
<td style="text-align: center;"><strong>Yes</strong></td>
<td style="text-align: center;"><strong>Yes</strong></td>
<td style="text-align: center;"><strong>Yes</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Black Box is unique in providing an <strong>information-theoretic ceiling</strong> and <strong>partial decomposition</strong> into component processes via the two-mode design.</p>
</div>
<aside class="notes">
<p>How Black Box compares to other reasoning benchmarks. Most benchmarks test constraint satisfaction or puzzle solving but lack key properties. Black Box is the only one that provides an information-theoretic ceiling — we can compute exactly how well a perfect agent would do. And it’s the only one that partially decomposes into component processes through the predict/play design. The ceiling is critical because it lets us measure not just whether models succeed or fail, but how far they are from optimal.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-this-means-for-diagnostic-ai" class="slide level2" data-background-color="#f8f9fa">
<h2>What This Means for Diagnostic AI</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="constraint-tracking">Constraint Tracking</h3>
<p>Models fail to maintain consistent evidence sets. <strong>Clinical risk</strong>: Contradicted diagnoses remain in differential.</p>
<h3 id="test-selection">Test Selection</h3>
<p>Models fire redundant/uninformative rays. <strong>Clinical risk</strong>: Unnecessary tests, delayed diagnosis.</p>
</div><div class="column" style="width:50%;">
<h3 id="scaling-limits">Scaling Limits</h3>
<p>Larger models help but don’t solve the problem. <strong>Clinical risk</strong>: Upgrading models doesn’t fix reasoning gaps.</p>
<h3 id="forward-inverse">Forward ≠ Inverse</h3>
<p>Good at prediction, poor at diagnosis. <strong>Clinical risk</strong>: Can explain findings but not generate differential.</p>
</div></div>
<aside class="notes">
<p>Four clinical implications. First, constraint tracking failures — models don’t maintain consistent evidence sets, so they’d fail to rule out conditions even when evidence is clear. Second, test selection — models choose uninformative tests, analogous to ordering redundant labs. Third, scaling doesn’t fix this — you can’t just use a bigger model. Fourth, the forward-inverse gap means models might be good at explaining test results but bad at generating the differential diagnosis in the first place.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-test-selection-problem" class="slide level2">
<h2>The Test Selection Problem</h2>

<img data-src="blackbox_presentation_files/figure-revealjs/ray-rank-histogram-1.png" width="1344" class="r-stretch"><div class="fragment">
<p><strong>Clinical analog</strong>: Choosing which diagnostic test to order next. Models rarely pick the most informative option — analogous to ordering a comprehensive metabolic panel when a single targeted test would be more informative.</p>
</div>
<aside class="notes">
<p>The test selection problem visualized. For each ray the model fires, we rank it among all 32 possible rays by information content. Rank 1 is the information-theoretically optimal choice. The distributions show that models rarely pick the optimal ray — they’re spread across the ranking, with many choosing rays ranked 5-15 out of 32. This is the clinical analog of choosing which test to order next. An optimal diagnostician picks the test that rules out the most conditions. LLMs pick tests somewhat informatively but far from optimal. In clinical practice, this manifests as redundant testing and delayed diagnosis.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="can-tools-fix-this" class="slide level2">
<h2>Can Tools Fix This?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="tools-can-help">Tools CAN Help</h3>
<ul>
<li><strong>Verification</strong>: Check if guess is consistent with constraints</li>
<li><strong>Computation</strong>: Enumerate candidate space</li>
<li><strong>Memory</strong>: Track accumulated evidence</li>
<li><strong>Visualization</strong>: Display board state</li>
</ul>
<p>LLM-Modulo architecture: use tools for verification, not generation.</p>
</div><div class="column" style="width:50%;">
<h3 id="tools-cant-help">Tools CAN’T Help</h3>
<ul>
<li><strong>Hypothesis generation</strong>: Must come from the model</li>
<li><strong>Test selection strategy</strong>: Model decides what to test</li>
<li><strong>Abductive inference</strong>: Reasoning from effects to causes</li>
<li><strong>Integration</strong>: Combining evidence across modalities</li>
</ul>
<p>The hardest parts of diagnosis are <strong>generative</strong>, not computational.</p>
</div></div>
<aside class="notes">
<p>A question from the field: can we just give LLMs tools to compensate? Partially. Tools can help with constraint checking — verifying whether a hypothesis is consistent with evidence. They can help with memory and computation. But the hard parts of diagnosis — generating hypotheses, choosing what to test, reasoning from effects to causes — are generative processes that must come from the model. No amount of tooling fixes poor abductive inference.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-good-benchmarks-need" class="slide level2">
<h2>What Good Benchmarks Need</h2>
<ol type="1">
<li class="fragment"><strong>Out-of-distribution problems</strong> — Not solvable by pattern matching to training data</li>
<li class="fragment"><strong>Information-theoretic ceiling</strong> — Know the best possible performance, not just pass/fail</li>
<li class="fragment"><strong>Decomposable</strong> — Isolate which component processes fail, not just overall accuracy</li>
<li class="fragment"><strong>Process-oriented</strong> — Test the reasoning process, not just the final answer</li>
</ol>
<div class="fragment">
<h3 id="a-challenge-to-the-field">A challenge to the field</h3>
<p>Most AI evaluation asks “<strong>can it get the right answer?</strong>”</p>
<p>We should be asking “<strong>does it reason correctly to get there?</strong>”</p>
</div>
<aside class="notes">
<p>Four properties that good diagnostic reasoning benchmarks should have. Most current benchmarks only satisfy one or two of these. Black Box satisfies all four, which is why it’s useful despite being a game rather than a clinical task. The broader challenge: the field focuses too much on outcome accuracy and not enough on process quality. A model that gets the right answer for the wrong reason is dangerous in clinical settings.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="limitations-future-work" class="slide level2">
<h2>Limitations &amp; Future Work</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="limitations">Limitations</h3>
<ul>
<li>Black Box is spatial; not all diagnosis is</li>
<li>2D grid; clinical reasoning is higher-dimensional</li>
<li>Fixed action space (32 rays); clinical tests are open-ended</li>
<li>Single-player; real diagnosis involves consultation</li>
<li>Currently only Claude models tested in React app</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="future-directions">Future Directions</h3>
<ul>
<li>Test more model families (GPT, Gemini, open-source)</li>
<li>Larger grids, more atoms</li>
<li>Multi-agent collaborative diagnosis</li>
<li>Transfer analysis: BB performance → clinical task performance</li>
<li>Agentic architectures with tool access</li>
</ul>
</div></div>
<aside class="notes">
<p>Honest limitations. Black Box is a spatial game, and not all diagnostic reasoning is spatial. The action space is constrained — in real medicine, you choose from thousands of possible tests. And we’ve only tested Claude models. Future work should test more models, explore multi-agent settings, and — most importantly — test whether Black Box performance predicts performance on actual clinical diagnostic tasks. That transfer analysis would validate the benchmark.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ol type="1">
<li class="fragment"><p><strong>LLMs perform above chance but far below optimal</strong> on diagnostic reasoning — extracting signal but failing at systematic evidence integration</p></li>
<li class="fragment"><p><strong>The failures are in the process, not the knowledge</strong> — models know ray physics but can’t select informative tests, track constraints, or recognize when evidence is sufficient</p></li>
<li class="fragment"><p><strong>Scaling and prompting help modestly</strong> — the diagnostic reasoning gap appears to be an architectural limitation, not an instructional one</p></li>
</ol>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Bottom Line</strong></p>
</div>
<div class="callout-content">
<p>Before deploying LLMs for diagnostic tasks, we need benchmarks that test <strong>reasoning process</strong>, not just <strong>answer accuracy</strong>. Black Box demonstrates that the gap between “knows the domain” and “reasons within the domain” is substantial and persistent.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Three takeaways to leave up during Q&amp;A. First, LLMs are somewhere between random and optimal — they’re not useless, but they’re far from reliable. Second, the problem isn’t knowledge but process — models know the rules, they just can’t apply them systematically over multiple steps. Third, bigger models and better prompts help a bit, but they don’t solve the fundamental problem. The bottom line for clinical deployment: we need much better evaluation before we trust LLMs with diagnostic reasoning.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="questions" class="slide level2" data-background-color="#2C3E50" style="color: white; text-align: center;">
<h2>Questions?</h2>
<div style="font-size: 1.3em; margin-top: 1em;">
<p><strong>Todd R. Johnson</strong></p>
<p>todd.r.johnson@uth.tmc.edu</p>
<p>University of Texas Health Science Center at Houston</p>
</div>
<div style="font-size: 1.1em; margin-top: 2em; color: #bdc3c7;">
<p>Paper &amp; Demo: <a href="https://github.com/toddjohnson/BBXReact">github.com/toddjohnson/BBXReact</a></p>
</div>
<div style="margin-top: 2em;">
<p><em>Happy to run additional live demos during Q&amp;A</em></p>
</div>
<aside class="notes">
<p>Open it up for questions. Offer to do more live demos if people want to see specific aspects of the game or the LLM’s behavior. The React app is running in another tab.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-bean2026reliability" class="csl-entry" role="listitem">
Bean, Andrew M et al. 2026. <span>“Reliability of LLMs as Medical Assistants for the General Public: A Randomized Preregistered Study.”</span> <em>Nature Medicine</em> 32: 609–15. <a href="https://doi.org/10.1038/s41591-025-04074-y">https://doi.org/10.1038/s41591-025-04074-y</a>.
</div>
<div id="ref-everson2025genai" class="csl-entry" role="listitem">
Everson, Jordan, Paige Nong, and Chelsea Richwine. 2025. <span>“Uptake of Generative AI Integrated with Electronic Health Records in US Hospitals.”</span> <em>JAMA Network Open</em> 8 (12): e2549463. <a href="https://doi.org/10.1001/jamanetworkopen.2025.49463">https://doi.org/10.1001/jamanetworkopen.2025.49463</a>.
</div>
<div id="ref-goh2024llmdiagnosis" class="csl-entry" role="listitem">
Goh, Ethan, Robert Gallo, Jason Hom, Eric Strong, Yingjie Weng, Hannah Kerman, Joséphine A Cool, et al. 2024. <span>“Large Language Model Influence on Diagnostic Reasoning: A Randomized Clinical Trial.”</span> <em>JAMA Network Open</em> 7 (10): e2440969. <a href="https://doi.org/10.1001/jamanetworkopen.2024.40969">https://doi.org/10.1001/jamanetworkopen.2024.40969</a>.
</div>
<div id="ref-johnson2001abductive" class="csl-entry" role="listitem">
Johnson, Todd R., and Josef F. Krems. 2001. <span>“Use of Current Explanations in Multicausal Abductive Reasoning.”</span> <em>Cognitive Science</em> 25 (6): 903–39. <a href="https://doi.org/10.1207/s15516709cog2506_2">https://doi.org/10.1207/s15516709cog2506_2</a>.
</div>
<div id="ref-klichowicz2021memory" class="csl-entry" role="listitem">
Klichowicz, Anja, Daniela Eileen Lippoldt, Agnes Rosner, and Josef F. Krems. 2021. <span>“Information Stored in Memory Affects Abductive Reasoning.”</span> <em>Psychological Research</em> 85 (8): 3119–33. <a href="https://doi.org/10.1007/s00426-020-01460-8">https://doi.org/10.1007/s00426-020-01460-8</a>.
</div>
<div id="ref-lang2023masai" class="csl-entry" role="listitem">
Lång, Kristina, Viktoria Josefsson, Anna-Maria Larsson, Stefan Larsson, Charlotte Högberg, Hanna Sartor, Solveig Hofvind, Ingvar Andersson, and Aldana Rosso. 2023. <span>“Artificial Intelligence–Supported Screen Reading Versus Standard Double Reading in the <span class="nocase">Mammography Screening with Artificial Intelligence</span> Trial (<span>MASAI</span>).”</span> <em>The Lancet Oncology</em> 24 (8): 936–44. <a href="https://doi.org/10.1016/S1470-2045(23)00298-X">https://doi.org/10.1016/S1470-2045(23)00298-X</a>.
</div>
<div id="ref-liu2024incomplete" class="csl-entry" role="listitem">
Liu, Emmy, Graham Neubig, and Jacob Andreas. 2024. <span>“An Incomplete Loop: Deductive, Inductive, and Abductive Learning in Large Language Models.”</span> <em>arXiv Preprint arXiv:2404.03028</em>.
</div>
<div id="ref-omar2025zebras" class="csl-entry" role="listitem">
Omar, Mahmud, Reem Agbareia, Alon Gorenshtein, Alexander W Charney, Benjamin S Glicksberg, Girish N Nadkarni, and Eyal Klang. 2025. <span>“Large Language Models Chase Zebras: Salient Cues Overrule Base Rates in Clinical Diagnosis.”</span> <em>SSRN Preprint</em>.
</div>
<div id="ref-plesner2024chestxray" class="csl-entry" role="listitem">
Plesner, Louis Lind, Felix C Müller, Mathias W Brejnebøl, Christian Hedeager Krag, Lene C Laustrup, Finn Rasmussen, Olav Wendelboe Nielsen, Mikael Boesen, and Michael B Andersen. 2024. <span>“Using <span>AI</span> to Identify Unremarkable Chest Radiographs for Automatic Reporting.”</span> <em>Radiology</em> 312 (2): e240272. <a href="https://doi.org/10.1148/radiol.240272">https://doi.org/10.1148/radiol.240272</a>.
</div>
<div id="ref-poon2025" class="csl-entry" role="listitem">
Poon, Eric G., Christy Harris Lemak, Juan C. Rojas, Janet Guptill, and David Classen. 2025. <span>“Adoption of Artificial Intelligence in Healthcare: Survey of Health System Priorities, Successes, and Challenges.”</span> <em>Journal of the American Medical Informatics Association</em>, ocaf065. <a href="https://doi.org/10.1093/jamia/ocaf065">https://doi.org/10.1093/jamia/ocaf065</a>.
</div>
<div id="ref-shojaee2025illusion" class="csl-entry" role="listitem">
Shojaee, Parshin, Iman Mirzadeh, Keivan Alizadeh, Maxwell Horton, Samy Bengio, and Mehrdad Farajtabar. 2025. <span>“The Illusion of Thinking: Understanding the Strengths and Limitations of Reasoning Models via the Lens of Problem Complexity.”</span> <em>arXiv Preprint arXiv:2506.06941</em>.
</div>
<div id="ref-shool2025systematic" class="csl-entry" role="listitem">
Shool, Sina, Sara Adimi, Reza Saboori Amleski, Ehsan Bitaraf, Reza Golpira, and Mahmood Tara. 2025. <span>“A Systematic Review of Large Language Model (<span>LLM</span>) Evaluations in Clinical Medicine.”</span> <em>BMC Medical Informatics and Decision Making</em> 25 (1): 117. <a href="https://doi.org/10.1186/s12911-025-02954-4">https://doi.org/10.1186/s12911-025-02954-4</a>.
</div>
<div id="ref-singhal2023medpalm2" class="csl-entry" role="listitem">
Singhal, Karan, Shekoofeh Azizi, Tao Tu, et al. 2023. <span>“Towards Expert-Level Medical Question Answering with Large Language Models.”</span> <em>Nature Medicine</em> 29: 2697–2705. <a href="https://doi.org/10.1038/s41591-023-02528-7">https://doi.org/10.1038/s41591-023-02528-7</a>.
</div>
<div id="ref-thirunavukarasu2023llmmed" class="csl-entry" role="listitem">
Thirunavukarasu, Arun James, Darren Shu Jeng Ting, Kabilan Elangovan, Laura Gutierrez, Ting Fang Tan, and Daniel Shu Wei Ting. 2023. <span>“Large Language Models in Medicine.”</span> <em>Nature Medicine</em> 29: 1930–40. <a href="https://doi.org/10.1038/s41591-023-02448-8">https://doi.org/10.1038/s41591-023-02448-8</a>.
</div>
<div id="ref-tu2024amie" class="csl-entry" role="listitem">
Tu, Tao, Anil Palepu, Mike Schaekermann, et al. 2024. <span>“Towards Conversational Diagnostic AI.”</span> <em>arXiv Preprint arXiv:2401.05654</em>. <a href="https://arxiv.org/abs/2401.05654">https://arxiv.org/abs/2401.05654</a>.
</div>
<div id="ref-wen2025context" class="csl-entry" role="listitem">
Wen, Andrew, Qiuhao Lu, Yu-Neng Chuang, et al. 2025. <span>“Context Matching Is Not Reasoning When Performing Generalized Clinical Evaluation of Generative Language Models.”</span> <em>Npj Digital Medicine</em>. <a href="https://doi.org/10.1038/s41746-025-02253-2">https://doi.org/10.1038/s41746-025-02253-2</a>.
</div>
<div id="ref-yu2024radiologist" class="csl-entry" role="listitem">
Yu, Feiyang, Alex Moehring, Oishi Banerjee, Tobias Salz, Nikhil Agarwal, and Pranav Rajpurkar. 2024. <span>“Heterogeneity and Predictors of the Effects of <span>AI</span> Assistance on Radiologists.”</span> <em>Nature Medicine</em> 30 (3): 837–49. <a href="https://doi.org/10.1038/s41591-024-02850-w">https://doi.org/10.1038/s41591-024-02850-w</a>.
</div>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="blackbox_presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="blackbox_presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="blackbox_presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="blackbox_presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>